# Generated by Django 4.2.1 on 2025-02-04 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_like_like_dislike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="blog",
        ),
        migrations.RemoveField(
            model_name="like",
            name="users",
        ),
        migrations.RemoveField(
            model_name="post",
            name="like",
        ),
        migrations.DeleteModel(
            name="Dislike",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
