# Generated by Django 4.2.1 on 2025-02-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_like_blog_remove_like_users_remove_post_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
