# Generated by Django 4.2.1 on 2025-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_header_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="header_image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
