# Generated by Django 4.2.1 on 2025-02-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="blog.post",
            ),
        ),
    ]
