# Generated by Django 4.2.1 on 2025-02-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_post_header_image_alter_postimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
