# Generated by Django 4.2.1 on 2025-02-10 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_blogcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogcomment",
            name="parent",
        ),
    ]
